### ISSUE TITLE
Delete predicate

### ISSUE THREAD

**Issue by giovannelli** [influxdata/influxdb-client-ruby#20] opened 2020-02-10 09:05 UTC
Hi there,
sorry to bother you again, but are you planning to add the delete endpoint to the gem?
Could you share the ETA for the first gem release?

Thank you,
Duccio

**Comment by bednar** [comment] 2020-02-10 09:15
Hi @giovannelli 

version 1.1.0 will be released this Friday. 

The `delete endpoint` is a good idea we will start works on it after #19 .

Regards

**Comment by giovannelli** [comment] 2020-02-10 09:53
@bednar thank you.

**Closed** 2020-02-25 10:08 UTC
Labels: enhancement

**Comment by bednar** [comment] 2020-02-25 10:14
Hi @giovannelli,

The issue is fixed in [1.2.0 milestone](https://github.com/influxdata/influxdb-client-ruby/milestone/3). 

If you would like to use a preview version use this gem: [ influxdb-client (1.2.0.pre.529) ](https://rubygems.org/gems/influxdb-client/versions/1.2.0.pre.529)

Regards
